export const Endpoints = {
    LOGIN_API : '/Employee/Login',
    EMPLOYEE_ROLE_API: '/Employee/GetRoleList',
    ADMIN_LIST_ROLE_API: '/Employee/GetAdminList',
    SUPERVISOR_LIST_ROLE_API: '/Employee/GetSupervisiorList',
    SAVE_EMPLOYEE: '/Employee/InsertEmployee',
    GET_ALL_EMPLOYEE: 'Employee/GetEmpbyAdmin',
    GET_ADMIN_ATTENDANCE: '/Attendance/GetAttDtlsAdByDate',
    GET_EMPLOYEE_ATTENDANCE: '/Attendance/GetAttendenceDtlsOfEmp',
    GET_EMPLOYEE_SUPERVISOR_ATTENDANCE: '/Attendance/GetEmployeeSupervisorAttendance',
    SAVE_ATTENDANCE: '/Attendance/saveAttendance',
    SAVE_PROFILE: '/Employee/SaveProfile',
    GET_EMPLOYEE_DETAILS_BY_ID: '/Employee/GetEmpdetailsbyId',
    GET_EMPLOYEE_TODAY_ATTENDANCE: '/Attendance/GetEmpTodayEntry',
    GET_SUPERVISORS_EMPLOYEE_LIST: '/Employee/GetEmpListForSuperV',
    MARK_ATTENDANCE: '/Attendance/markAttendance',
    GET_ADMIN_ATTENDANCE_COUNT: '/Attendance/GetAttCountDtlsAd',
    CHANGE_PASSWORD: '/Employee/ChangePassword',
    SAVE_TASK: 'Task/insUpdEmployeeTask',
    GET_TASK_DETAILS: 'Task/GetTaskDtlsForEmp',
    DELETE_TASK: 'Task/delTaskOfEmp',
}