export const EMPLOYEE_TASK_TITLE = 'EMPLOYEE_TASK_TITLE'
export const SUPERVISOR_TASK_TITLE = 'SUPERVISOR_TASK_TITLE'
export const ADD_TASK_TITLE = 'ADD_TASK_TITLE'
export const UPDATE_TASK_TITLE = 'UPDATE_TASK_TITLE'
export const EMPLOYEE_TASK_CONSTANT = {
  TITLE: 'EMPLOYEE_TASK_CONSTANT.TITLE',
  DESCRIPTION: 'EMPLOYEE_TASK_CONSTANT.DESCRIPTION',
  START_DATE: 'EMPLOYEE_TASK_CONSTANT.START_DATE',
  END_DATE: 'EMPLOYEE_TASK_CONSTANT.END_DATE',
  STATUS: 'EMPLOYEE_TASK_CONSTANT.STATUS',
  PHOTO: 'EMPLOYEE_TASK_CONSTANT.PHOTO',
};
export const TASK_NAME_CONSTANT = {
    LABEL: 'TASK_NAME_CONSTANT.LABEL',
    PLACEHOLDER: 'TASK_NAME_CONSTANT.PLACEHOLDER',
    NAME: 'title',
    REQUIRED_ERROR: 'TASK_NAME_CONSTANT.REQUIRED_ERROR',
};
export const TASK_DESCRIPTION_CONSTANT = {
    LABEL: 'TASK_DESCRIPTION_CONSTANT.LABEL',
    PLACEHOLDER: 'TASK_DESCRIPTION_CONSTANT.PLACEHOLDER',
    NAME: 'description',
};
export const START_DATE_CONSTANT = {
    LABEL: 'START_DATE_CONSTANT.LABEL',
    NAME: 'startDate',
    PLACEHOLDER: 'START_DATE_CONSTANT.PLACEHOLDER',
    REQUIRED_ERROR: 'START_DATE_CONSTANT.REQUIRED_ERROR',
};
export const END_DATE_CONSTANT = {
    LABEL: 'END_DATE_CONSTANT.LABEL',
    NAME: 'endDate',
    PLACEHOLDER: 'END_DATE_CONSTANT.PLACEHOLDER',
};
export const TASK_PHOTO_CONSTANT = {
    LABEL: 'TASK_PHOTO_CONSTANT.LABEL',
    PLACEHOLDER: 'TASK_PHOTO_CONSTANT.PLACEHOLDER',
    NAME: 'photo',
};