export const LOGOUT_CONSTANT = {
    CONFIRM_LABEL: 'CONFIRM_LOGOUT',
    LOGOUT_LABEL: 'LOGOUT_MESSAGE',
    CANCEL_TEXT: 'CANCEL_TEXT',
    CANCEL_STYLE: 'cancel',
    YES_TEXT: 'YES_TEXT',
    LOG_OUT_TEXT: 'LOG_OUT_TEXT'
}   