export const LOGOUT_CONSTANT = {
    CONFIRM_LABEL: 'CONFIRM_LOGOUT',
    LOGOUT_LABEL: 'LOGOUT_MESSAGE',
    CANCEL_TEXT: 'CANCEL_TEXT',
    CANCEL_STYLE: 'cancel',
    YES_TEXT: 'YES_TEXT',
    LOG_OUT_TEXT: 'LOG_OUT_TEXT'
}   
export const PROFILE_CONSTANT = {
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    TERMS_CONDITIONS: 'TERMS_CONDITIONS',
    PRIVACY_POLICY: 'PRIVACY_POLICY',
    PASSWORD_PATTERN: /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d@$!%*?&]{6,}$/
}
export const CURRENT_PASSWORD_CONSTANT = {
    LABEL: 'CURRENT_PASSWORD_LABEL',
    PLACEHOLDER: 'CURRENT_PASSWORD_PLACEHOLDER',
    NAME: 'currPwd',
    REQUIRED_ERROR: 'CURRENT_PASSWORD_ERROR',
};
export const NEW_PASSWORD_CONSTANT = {
    LABEL: 'NEW_PASSWORD_LABEL',
    PLACEHOLDER: 'NEW_PASSWORD_PLACEHOLDER',
    NAME: 'newPwd',
    REQUIRED_ERROR: 'NEW_PASSWORD_ERROR',
    PASSWORD_PATTERN_ERROR: 'PASSWORD_PATTERN_ERROR'
};
export const CONFIRM_PASSWORD_CONSTANT = {
    LABEL: 'CONFIRM_PASSWORD_LABEL',
    PLACEHOLDER: 'CONFIRM_PASSWORD_PLACEHOLDER',
    NAME: 'cnfmPwd',
    REQUIRED_ERROR: 'CONFIRM_PASSWORD_ERROR',
    CONFIRM_PASSWORD_MATCH_ERROR: 'CONFIRM_PASSWORD_MATCH_ERROR'
};