export const ATTENDANCE_CONSTANT = {
    DAY: 'DAY',
    CHECK_IN: 'CHECK_IN',
    CHECK_OUT: 'CHECK_OUT',
    TOTAL_HOUR: 'TOTAL_HOUR',
    LOCATION: 'LOCATION',
    DATE: 'DATE',
    NAME: 'NAME',
    ROLE: 'ROLE',
    STATUS: 'STATUS',
    NO_DATA: '--',
    CHECK_LOCATION: 'CHECK_LOCATION',
    SUPERVISOR_ROLE: 'Supervisor',
    EMPLOYEE_ROLE: 'Employee',
    PRESENT: 'Present',
    ABSENT: 'Absent'
}
export const MY_ATTENDANCE_TITLE = 'MY_ATTENDANCE_TITLE'
export const EMPLOYEE_ATTENDANCE_TITLE = 'EMPLOYEE_ATTENDANCE_TITLE'
export const ATTENDANCE_COUNT_CARD_CONSTANT = {
    DATE_MODE: 'date',
    DEFAULT: 'default',
    TOTAL: 'TOTAL',
    PRESENT: 'PRESENT',
    ABSENT: 'ABSENT'
}
export const ATTENDANCE_STATUS = {
    PRESENT: 'present',
    ABSENT: 'absent'
}
export const MARK_ATTENDANCE_TITLE = 'MARK_ATTENDANCE'
export const SET_EMPLOYEE_ATTENDANCE = {
    FRONT_CAMERA: 'front',
    BACK_CAMERA: 'back',
    GRANTED_STATUS: 'granted',
    DENIED_CAMERA_PERMISSION: 'Camera permission not granted',
    DENIED_LOCATION: 'DENIED_LOCATION',
    CAMERA_NOT_READY: 'Camera not ready!',
    FLASH_OFF: 'off',
    CHECK_IN_SUCCESS: 'Check-In Successful',
    CHECK_OUT_SUCCESS: 'Check-Out Successful',
    FAILED_IMAGE: 'Failed to capture image',
    LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
    CAMERA_PERMISSION_REQUIRED: 'CAMERA_PERMISSION_REQUIRED',
    LOADING_CAMERA: 'Loading Camera...'
}
export const CAMERA_CONSTANT = {
    CANCEL_LABEL: 'CAMERA_CANCEL_LABEL',
    CANCEL_MSG: 'CAMERA_CANCEL_MSG',
    CAMERA_ERROR: 'CAMERA_ERROR',
    UNKNOWN_ERROR_MSG: 'CAMERA_UNKNOWN_ERROR_MSG',
    ERROR_TEXT: 'CAMERA_ERROR_TEXT',
    ERROR_MSG: 'CAMERA_ERROR_MSG',
    ERROR_MSG_1: 'CAMERA_ERROR_MSG_1'
}
export const GEOFENCE_CONSTANT = {
    LABEL: 'GEOFENCE_LABEL',
    MSG: 'GEOFENCE_MSG'
}

export const MOCK_LOCATION_CONSTANT = {
    LABEL: 'MOCK_LOCATION_LABEL',
    MSG: 'MOCK_LOCATION_MSG'
}

export const MOCK_TIME_CONSTANT = {
    LABEL: 'MOCK_TIME_LABEL',
    MSG: 'MOCK_TIME_MSG'
}