# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# react-native-permissions setup
require_relative '../node_modules/react-native-permissions/scripts/setup.rb'

platform :ios, min_ios_version_supported
prepare_react_native_project!

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-maps/Google', :path => rn_maps_path
pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec', :modular_headers => true

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'attendrix' do
  config = use_native_modules!
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  use_react_native!(
    :path => config[:reactNativePath],
    # Absolute path to app root
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  setup_permissions([
    'Camera',
    'LocationAccuracy',
    'LocationAlways',
    'LocationWhenInUse',
    'MediaLibrary',
    'Microphone',
    'PhotoLibrary',
    'PhotoLibraryAddOnly',
  ])

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix duplicate React-Core_privacy.bundle issue
    installer.pods_project.targets.each do |target|
      if target.name.include?("React-Core")
        target.build_phases.each do |phase|
          if phase.respond_to?(:name) && phase.name == 'Copy Bundle Resources'
            phase.files.each do |file|
              if file.display_name == "React-Core_privacy.bundle"
                phase.remove_file_reference(file.file_ref)
              end
            end
          end
        end
      end
    end
  end
end
