export const REPORT_CONSTANT = {
  REPORT_TITLE: 'REPORT_CONSTANT.REPORT_TITLE',
  ATTENDANCE_REPORT: 'REPORT_CONSTANT.ATTENDANCE_REPORT',
  TASK_REPORT: 'REPORT_CONSTANT.TASK_REPORT',
  FILTERS: 'REPORT_CONSTANT.FILTERS',
  EMPLOYEE: 'REPORT_CONSTANT.EMPLOYEE',
  CLEAR: 'REPORT_CONSTANT.CLEAR',
  SUBMIT: 'REPORT_CONSTANT.SUBMIT',
  EXPORT: 'REPORT_CONSTANT.EXPORT'
}

export const EMPLOYEE_CONSTANT = {
  LABEL: 'EMPLOYEE_CONSTANT.LABEL',
  PLACEHOLDER: 'EMPLOYEE_CONSTANT.PLACEHOLDER',
  NAME: 'employee',
  REQUIRED_ERROR: 'EMPLOYEE_CONSTANT.REQUIRED_ERROR',
}

export const FROM_DATE_CONSTANT = {
  LABEL: 'FROM_DATE_CONSTANT.LABEL',
  PLACEHOLDER: 'FROM_DATE_CONSTANT.PLACEHOLDER',
  NAME: 'fromDate',
  REQUIRED_ERROR: 'FROM_DATE_CONSTANT.REQUIRED_ERROR',
}

export const TO_DATE_CONSTANT = {
  LABEL: 'TO_DATE_CONSTANT.LABEL',
  PLACEHOLDER: 'TO_DATE_CONSTANT.PLACEHOLDER',
  NAME: 'toDate',
  REQUIRED_ERROR: 'TO_DATE_CONSTANT.REQUIRED_ERROR',
}

export const ATTENDANCE_HEADERS = [
  'SR_NO',
  'EMPLOYEE_NAME',
  'ROLE',
  'CHECK_IN',
  'CHECK_OUT',
  'TOTAL_HOURS',
  'MARKED_BY'
];

export const GRAPH_CONSTANT = {
  TOTAL_HRS: 'Total Hrs',
  EMP_ATTENDANCE_DATES: 'Employee Attendance Dates',
  NO_TASK: 'Number of Tasks',
  EMP_TASK_DATES: 'Employee Task Dates'
}
