export const CHECK_IN_LABEL = 'CHECK_IN_LABEL';
export const CHECK_OUT_LABEL = 'CHECK_OUT_LABEL';
export const NO_TIME = '--/--';
export const CATEGORY_TITLE = 'CATEGORY_TITLE';
export const CATERGORY_CONSTANT = {
    ATTENDANCE: 'ATTENDANCE',
    REPORTS: 'REPORTS',
    EMPLOYEES: 'EMPLOYEES',
    MARK_ATTENDANCE: 'MARK_ATTENDANCE',
    MY_ATTENDANCE: 'MY_ATTENDANCE',
    MY_TASK: 'MY_TASK',
    EMPLOYEE_TASK: 'EMPLOYEE_TASK',
    SET_LOCATION: 'SET_LOCATION'
}
export const MANAGE_TASK = 'MANAGE_TASK';
export const SELF_TASK = 'SELF_TASK';
export const CHECK_TASK = 'CHECK_TASK';
export const NOTIFICATION_CONSTANT = {
    NOTIFICATION_TITLE: 'NOTIFICATION_TITLE',
    MARK_ALL_READ: 'MARK_ALL_READ'
}