const MyImages = {
    app_logo: require('../assets/images/attendrix_logo_21.png'),
    view: require('../assets/images/view.png'),
    hide: require('../assets/images/hide.png'),
    goBack: require('../assets/images/back-button.png'),
    setting: require('../assets/images/settings.png'),
    goFurther: require('../assets/images/fast-forward.png'),
    checkIn: require('../assets/images/check-in.png'),
    checkOut: require('../assets/images/exit.png'),
    attendance: require('../assets/images/attendance.png'),
    profile: require('../assets/images/profile.png'),
    task: require('../assets/images/task.png'),
    report: require('../assets/images/report.png'),
    employee: require('../assets/images/team.png'),
    totalEmployees: require('../assets/images/totalEmployees.png'),
    presentEmployees: require('../assets/images/presentEmployees.png'),
    absentEmployees: require('../assets/images/absentEmployees.png'),
    noData: require('../assets/images/no-data.png'),
    calendar: require('../assets/images/calendar.png'),
    cancel: require('../assets/images/cancel.png'),
    add: require('../assets/images/add.png'),
    edit: require('../assets/images/edit.png'),
    flip: require('../assets/images/flip.png'),
    rightArrow: require('../assets/images/right-arrow.png'),
    termsConditions: require('../assets/html/attendrixTermsConditions.html'),
    privacyPolicy: require('../assets/html/attendrixPrivacyPolicy.html'),
    noPhoto: require('../assets/images/no-camera.png'),
    close: require('../assets/images/close.png'),
    delete: require('../assets/images/delete.png')
}

export default MyImages;