export const SET_LOCATION_CONSTANT = {
    NO_EMPLOYEE_SELECTED: 'NO_EMPLOYEE_SELECTED',
    SET_LOCATION: 'SET_LOCATION_LABEL',
    SET_WORKING_LOCATION_TITLE: 'SET_WORKING_LOCATION_TITLE',
    SELECTED_EMPLOYEES: 'SELECTED_EMPLOYEES',
    SAVE: 'SAVE',
    WORKING_LOCATION: 'WORKING_LOCATION',
    NO_TIME: '--/--'
}

export const SET_LOCATION_DROPDOWN = {
    NAME: 'location',
    LABEL: 'DROPDOWN_LABEL',
    PLACEHOLDER: 'DROPDOWN_PLACEHOLDER',
    REQUIRED_ERROR: 'DROPDOWN_REQUIRED_ERROR'
}