export const MANAGE_EMPLOYEE_TITLE = 'MANAGE_EMPLOYEE_TITLE'
export const ADD_EMPLOYEE_TITLE = 'ADD_EMPLOYEE_TITLE'
export const UPDATE_EMPLOYEE_TITLE = 'UPDATE_EMPLOYEE_TITLE'
export const NUMBER_KEYPAD = 'numeric'
export const MANAGE_EMPLOYEE_CONSTANT = {
    ADD_MODE: 'add',
    UPDATE_MODE: 'update',
    MOBILE: 'MOBILE',
    ROLES: 'ROLES',
    JOINING_DATE: 'JOINING_DATE',
    ADDRESS: 'ADDRESS',
    CHECK_ATTENDANCE: 'CHECK_ATTENDANCE',
    REPORTING_MANAGER: 'REPORTING_MANAGER',
    SET_ATTENDANCE: 'SET_ATTENDANCE'
}
export const NAME_CONSTANT = {
    LABEL: 'NAME_LABEL',
    PLACEHOLDER: 'NAME_PLACEHOLDER',
    NAME: 'name',
    REQUIRED_ERROR: 'NAME_REQUIRED_ERROR',
};
export const MOBILE_CONSTANT = {
    LABEL: 'MOBILE_LABELS',
    PLACEHOLDER: 'MOBILE_PLACEHOLDERS',
    NAME: 'mobile',
    REQUIRED_ERROR: 'MOBILE_REQUIRED_ERRORS',
    PATTERN_1: /^[0-9]{10}$/,
    PATTERN_ERROR: 'MOBILE_PATTERN_ERRORS'
};
export const REPORTING_MANAGER_CONSTANT = {
    LABEL: 'REPORTING_MANAGER_LABEL',
    PLACEHOLDER: 'REPORTING_MANAGER_PLACEHOLDER',
    NAME: 'reportingManager',
    REQUIRED_ERROR: 'REPORTING_MANAGER_REQUIRED_ERROR',
};
export const ROLE_CONSTANT = {
    LABEL: 'ROLE_LABEL',
    PLACEHOLDER: 'ROLE_PLACEHOLDER',
    NAME: 'role',
    REQUIRED_ERROR: 'ROLE_REQUIRED_ERROR',
};
export const JOINIG_DATE_CONSTANT = {
    LABEL: 'JOINING_DATE_LABEL',
    NAME: 'joiningDate',
    PLACEHOLDER: 'JOINING_DATE_PLACEHOLDER',
    REQUIRED_ERROR: 'JOINING_DATE_REQUIRED_ERROR',
};
export const ADDRESS_CONSTANT = {
    LABEL: 'ADDRESS_LABEL',
    PLACEHOLDER: 'ADDRESS_PLACEHOLDER',
    NAME: 'address',
    REQUIRED_ERROR: 'ADDRESS_REQUIRED_ERROR',
};
export const LEAVING_DATE_CONSTANT = {
    LABEL: 'LEAVING_DATE_LABEL',
    NAME: 'leavingDate',
    PLACEHOLDER: 'LEAVING_DATE_PLACEHOLDER',
};